const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const start={day:1,money:300,rank:'ヒョロ期',muscle:8,power:8,stamina:8,mental:12,bodyFat:18,fatigue:10,nutrition:45,fistPower:5,fistSpeed:5,core:5,stomach:8,eatingSpeed:7,digestion:8,titles:[],log:['ガチマッチョ育成、開始！まずは無理せず鍛えよう。']};
const labels={muscle:'筋肉量',power:'パワー',stamina:'持久力',mental:'メンタル',bodyFat:'体脂肪率',fatigue:'疲労度',nutrition:'栄養状態',fistPower:'拳力',fistSpeed:'拳速',core:'体幹力',stomach:'胃袋容量',eatingSpeed:'食速',digestion:'消化力'};
const menus={train:[['🏋️','ベンチプレス',20,{muscle:4,power:5,fatigue:14,nutrition:-8},'胸板とパワーを鍛える王道メニュー。'],['🦵','スクワット',20,{muscle:3,power:4,stamina:3,core:2,fatigue:16,nutrition:-10},'脚と体幹を鍛える。パンチにも効く。'],['🥊','サンドバッグ打ち',25,{fistPower:5,fistSpeed:3,power:2,fatigue:15,nutrition:-8},'拳力と拳速を鍛える。'],['🔥','体幹トレーニング',15,{core:5,stamina:2,fatigue:10,nutrition:-5},'ブレない身体を作る。'],['🍚','食事トレーニング',20,{stomach:5,eatingSpeed:3,digestion:2,bodyFat:2,fatigue:8,nutrition:-4},'胃袋容量と食速を鍛える。']],meal:[['🍗','鶏むね定食',35,{nutrition:24,muscle:2,bodyFat:-1},'高たんぱくで筋肉成長。'],['🥩','牛肉メガ盛り丼',55,{nutrition:35,power:3,stomach:2,bodyFat:3},'パワーと胃袋が伸びる。'],['🥤','プロテイン',25,{nutrition:16,muscle:1,fatigue:-3},'手軽に栄養補給。'],['🍛','激辛カレー',40,{nutrition:22,mental:4,digestion:2,bodyFat:1,fatigue:5},'メンタルと消化力を鍛える。']],rest:[['😴','しっかり睡眠',0,{fatigue:-28,mental:5,nutrition:-4},'筋肉にも有給休暇が必要。'],['♨️','温泉回復',45,{fatigue:-40,mental:10,digestion:2},'疲労とメンタルを回復。'],['🚶','軽い散歩',0,{fatigue:-12,stamina:1,bodyFat:-1,digestion:2},'コンディション調整。']]};
const ranks=[['神域マッチョ期',170],['レジェンドマッチョ期',135],['ガチマッチョ期',105],['バルクアップ期',75],['細マッチョ期',50],['初心者トレーニー期',30],['ヒョロ期',0]];
let p=JSON.parse(JSON.stringify(start)),tab='train',last=null;
function apply(e){Object.entries(e).forEach(([k,v])=>p[k]=(p[k]??0)+v);['muscle','power','stamina','mental','fistPower','fistSpeed','core','stomach','eatingSpeed','digestion'].forEach(k=>p[k]=clamp(p[k],0,220));p.bodyFat=clamp(p.bodyFat,5,45);p.fatigue=clamp(p.fatigue,0,100);p.nutrition=clamp(p.nutrition,0,100);let total=p.muscle+p.power+p.stamina+p.fistPower+p.core+p.stomach;p.rank=ranks.find(r=>total>=r[1])[0];}
function log(m){p.log=[m,...p.log].slice(0,8)}
function day(){apply({fatigue:p.fatigue>75?4:-2,nutrition:-5,mental:p.fatigue>80?-3:1});p.day++;if(p.nutrition<15){apply({muscle:-2,power:-1,mental:-1});log('栄養不足で筋肉がしぼんだ……食わせよう。')}if(p.fatigue>90){apply({power:-2,fistPower:-2,stamina:-2,mental:-3});log('疲労が限界！今日は寝よう。')}}
function act(i){const m=menus[tab][i];if(p.money<m[2])return;p.money-=m[2];apply(m[3]);log(`${m[1]}を実行。成果が出た！`);day();last=null;render()}
function sBody(){const fat=Math.max(0,30-Math.abs(p.bodyFat-12)*2);return Math.round(p.muscle*1.4+p.core*.6+p.mental*.4+fat-p.fatigue*.7)}
function sPunch(){return Math.round(p.fistPower*1.25+p.power*.8+p.core*.7+p.fistSpeed*.6+p.mental*.4-p.fatigue*.75)}
function sEat(){return Math.round(p.eatingSpeed*1.15+p.stomach*1.05+p.digestion*.8+p.mental*.5-p.fatigue*.45-Math.max(0,p.bodyFat-28)*.5)}
const comps=[['🏆','ボディメイク大会',95,150,sBody,'地方ボディメイク王','筋肉量・体脂肪率・体幹で勝負。'],['🥊','パンチ大会',105,170,sPunch,'拳で語るマッチョ','拳力・パワー・体幹・拳速で勝負。'],['🍚','早食い大会',100,165,sEat,'胃袋ブラックホール','食速・胃袋容量・消化力で勝負。']];
function battle(i){const c=comps[i],score=c[4]()+Math.floor(Math.random()*31)-10,win=score>=c[2];if(win){p.money+=c[3];p.mental=clamp(p.mental+8,0,220);if(!p.titles.includes(c[5]))p.titles.push(c[5]);log(`${c[1]}で勝利！称号「${c[5]}」を獲得。`)}else{p.mental=clamp(p.mental-4,0,220);log(`${c[1]}は惜しくも敗北。筋肉会議で反省しよう。`)}apply({fatigue:12,nutrition:-8});day();last={name:c[1],score,target:c[2],win,reward:win?c[3]:0};render()}
function bar(name,v,max=100){return `<div><div class='label'><span>${name}</span><span>${Math.round(v)}</span></div><div class='bar'><i style='width:${clamp(v/max*100,0,100)}%'></i></div></div>`}
function render(){let size=clamp(90+p.muscle*.55,90,190),belly=clamp(p.bodyFat*1.4,16,55),arm=clamp(12+p.power*.12,12,38);q('hero').innerHTML=`<div class='card hero'><div class='man'><div class='face'>筋</div><div class='row'><div class='arm' style='width:${arm}px;height:${size*.65}px'></div><div class='body' style='width:${size*.72+belly}px;height:${size}px'><div class='abs'><span></span><span></span><span></span><span></span></div></div><div class='arm' style='width:${arm}px;height:${size*.65}px'></div></div><div class='legs'><div class='leg'></div><div class='leg'></div></div></div><div class='rank'><strong>${p.rank}</strong><br><span>Day ${p.day} / 所持金 ${p.money}G</span></div></div>`;q('condition').textContent=p.fatigue>85?'危険：今日は休ませたい。':p.nutrition<20?'栄養不足：食事を入れよう。':p.mental<15?'メンタル低下：休養しよう。':'良好：鍛えるか大会に挑戦できる。';q('stats').innerHTML=bar('筋肉量',p.muscle,180)+bar('パワー',p.power,180)+bar('持久力',p.stamina,180)+bar('メンタル',p.mental,180)+bar('拳力',p.fistPower,180)+bar('拳速',p.fistSpeed,180)+bar('体幹力',p.core,180)+bar('胃袋容量',p.stomach,180)+bar('食速',p.eatingSpeed,180)+bar('消化力',p.digestion,180)+bar('栄養状態',p.nutrition,100)+bar('疲労度',p.fatigue,100);q('titles').innerHTML=p.titles.length?`<div class='titles'>${p.titles.map(t=>`<span>${t}</span>`).join('')}</div>`:`<p class='sub'>まだ称号なし。大会で筋肉の名を刻もう。</p>`;q('tabs').innerHTML=[['train','🏋️ 鍛える'],['meal','🍗 食べる'],['rest','😴 休む'],['battle','🏆 大会']].map(x=>`<button class='btn ${tab===x[0]?'on':''}' onclick="tab='${x[0]}';render()">${x[1]}</button>`).join('');q('result').innerHTML=last?`<div class='card result'><span class='sub'>大会結果</span><strong>${last.name}：${last.win?'勝利！':'敗北……'}</strong><p>スコア ${last.score} / 目標 ${last.target}${last.reward?`　報酬 ${last.reward}G`:''}</p></div>`:'';if(tab==='battle'){q('actions').innerHTML=comps.map((c,i)=>`<div class='card action'><h3>${c[0]} ${c[1]}</h3><p>${c[6]}</p><div class='effects'>予想スコア ${c[4]()} / 勝利目標 ${c[2]}<br>勝利報酬 ${c[3]}G</div><button class='btn main' onclick='battle(${i})'>出場する</button></div>`).join('')}else{q('actions').innerHTML=menus[tab].map((m,i)=>`<div class='card action'><h3>${m[0]} ${m[1]}</h3><p>${m[4]}</p><div class='effects'>${Object.entries(m[3]).map(([k,v])=>`${labels[k]}${v>0?'+':''}${v}`).join(' ')}</div><button class='btn main' ${p.money<m[2]?'disabled':''} onclick='act(${i})'>${m[2]?m[2]+'Gで実行':'実行'}</button></div>`).join('')}q('log').innerHTML=p.log.map(l=>`<div>${l}</div>`).join('')}
function q(id){return document.getElementById(id)}
q('reset').onclick=()=>{p=JSON.parse(JSON.stringify(start));tab='train';last=null;render()};render();
